"""order item unit price and order corrections audit

Revision ID: 9af23169fc6f
Revises: a2447c7b056b
Create Date: 2026-06-20 13:56:26.049553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af23169fc6f'
down_revision: Union[str, None] = 'a2447c7b056b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('before_items', sa.JSON(), nullable=True),
    sa.Column('after_items', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_corrections_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('unit_price_cents')

    with op.batch_alter_table('order_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_corrections_order_id'))

    op.drop_table('order_corrections')
    # ### end Alembic commands ###
