"""order fulfillment flags

Revision ID: a2447c7b056b
Revises: 81176b5b1dbd
Create Date: 2026-06-20 08:42:54.026036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2447c7b056b'
down_revision: Union[str, None] = '81176b5b1dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_email_sent', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('delivered', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivered')
        batch_op.drop_column('confirmation_email_sent')

    # ### end Alembic commands ###
